### ISSUE TITLE
Windower crashes immediately on load

### ISSUE THREAD

**Issue by Caffeinator1** [Windower/Issues#1002]
Windower is not hooking to POL. I see the green Windower4 load icon followed by nothing.  

Here is a photo of the Windower4 details.
[Details](https://drive.google.com/file/d/1JE0MDUrm0TrY2eQypht0Uomsok19ATF9/view?usp=sharing)

Here is the crash.log:
``````````````````````````````````````````````````````````````````````
5/29/2018 5:59:26 PM
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully
   at #=q2j__O48iHJA1sJusReyDbbwrLiSkzwNLqrwH6$iE6$o=.#=qY2KRvVSnPBFI46oP9bXkveu3IxN5VFsaRub_4yzULfY=()
   at #=qmhNvAyztrFon0QQMItVoEw==.#=qwPLw4iF7BpHxtYPS54bKjfLINL4BHtYz0Vz27lRRwew=()
   at #=qmhNvAyztrFon0QQMItVoEw==..ctor()
   at Launcher.LauncherApplication..ctor(SplashScreen #=qf1N4B_PrqOdTNDSUbsv80w==)
   at #=qnTC76DU__og_WMgWCrTYvRcQxL1W079cH4guBwcE_Ec=.#=qFBpVS932WqoZvE_tXrbxgw==()
   at #=qPUOOy9u5HdURknzeezer4ma9AtDiJSThgKqArWsT_GU=.#=qt4kp1W4B7EWJTkNhTHr5uA==()
`````````````````````````````````````````````````````````````````````

`````````````````````````````````````````````````````````````````````
5/29/2018 5:59:55 PM
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully
   at #=q2j__O48iHJA1sJusReyDbbwrLiSkzwNLqrwH6$iE6$o=.#=qY2KRvVSnPBFI46oP9bXkveu3IxN5VFsaRub_4yzULfY=()
   at #=qmhNvAyztrFon0QQMItVoEw==.#=qwPLw4iF7BpHxtYPS54bKjfLINL4BHtYz0Vz27lRRwew=()
   at #=qmhNvAyztrFon0QQMItVoEw==..ctor()
   at Launcher.LauncherApplication..ctor(SplashScreen #=qf1N4B_PrqOdTNDSUbsv80w==)
   at #=qnTC76DU__og_WMgWCrTYvRcQxL1W079cH4guBwcE_Ec=.#=qFBpVS932WqoZvE_tXrbxgw==()
   at #=qPUOOy9u5HdURknzeezer4ma9AtDiJSThgKqArWsT_GU=.#=qt4kp1W4B7EWJTkNhTHr5uA==()
`````````````````````````````````````````````````````````````````````

`````````````````````````````````````````````````````````````````````
5/29/2018 6:01:59 PM
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully
   at #=q2j__O48iHJA1sJusReyDbbwrLiSkzwNLqrwH6$iE6$o=.#=qY2KRvVSnPBFI46oP9bXkveu3IxN5VFsaRub_4yzULfY=()
   at #=qmhNvAyztrFon0QQMItVoEw==.#=qwPLw4iF7BpHxtYPS54bKjfLINL4BHtYz0Vz27lRRwew=()
   at #=qmhNvAyztrFon0QQMItVoEw==..ctor()
   at Launcher.LauncherApplication..ctor(SplashScreen #=qf1N4B_PrqOdTNDSUbsv80w==)
   at #=qnTC76DU__og_WMgWCrTYvRcQxL1W079cH4guBwcE_Ec=.#=qFBpVS932WqoZvE_tXrbxgw==()
   at #=qPUOOy9u5HdURknzeezer4ma9AtDiJSThgKqArWsT_GU=.#=qt4kp1W4B7EWJTkNhTHr5uA==()
`````````````````````````````````````````````````````````````````````

`````````````````````````````````````````````````````````````````````
5/29/2018 6:04:39 PM
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully
   at #=q2j__O48iHJA1sJusReyDbbwrLiSkzwNLqrwH6$iE6$o=.#=qY2KRvVSnPBFI46oP9bXkveu3IxN5VFsaRub_4yzULfY=()
   at #=qmhNvAyztrFon0QQMItVoEw==.#=qwPLw4iF7BpHxtYPS54bKjfLINL4BHtYz0Vz27lRRwew=()
   at #=qmhNvAyztrFon0QQMItVoEw==..ctor()
   at Launcher.LauncherApplication..ctor(SplashScreen #=qf1N4B_PrqOdTNDSUbsv80w==)
   at #=qnTC76DU__og_WMgWCrTYvRcQxL1W079cH4guBwcE_Ec=.#=qFBpVS932WqoZvE_tXrbxgw==()
   at #=qPUOOy9u5HdURknzeezer4ma9AtDiJSThgKqArWsT_GU=.#=qt4kp1W4B7EWJTkNhTHr5uA==()
`````````````````````````````````````````````````````````````````````

`````````````````````````````````````````````````````````````````````
5/29/2018 6:06:37 PM
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully
   at #=q2j__O48iHJA1sJusReyDbbwrLiSkzwNLqrwH6$iE6$o=.#=qY2KRvVSnPBFI46oP9bXkveu3IxN5VFsaRub_4yzULfY=()
   at #=qmhNvAyztrFon0QQMItVoEw==.#=qwPLw4iF7BpHxtYPS54bKjfLINL4BHtYz0Vz27lRRwew=()
   at #=qmhNvAyztrFon0QQMItVoEw==..ctor()
   at Launcher.LauncherApplication..ctor(SplashScreen #=qf1N4B_PrqOdTNDSUbsv80w==)
   at #=qnTC76DU__og_WMgWCrTYvRcQxL1W079cH4guBwcE_Ec=.#=qFBpVS932WqoZvE_tXrbxgw==()
   at #=qPUOOy9u5HdURknzeezer4ma9AtDiJSThgKqArWsT_GU=.#=qt4kp1W4B7EWJTkNhTHr5uA==()
`````````````````````````````````````````````````````````````````````

`````````````````````````````````````````````````````````````````````
5/29/2018 6:11:04 PM
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully
   at #=q2j__O48iHJA1sJusReyDbbwrLiSkzwNLqrwH6$iE6$o=.#=qY2KRvVSnPBFI46oP9bXkveu3IxN5VFsaRub_4yzULfY=()
   at #=qmhNvAyztrFon0QQMItVoEw==.#=qwPLw4iF7BpHxtYPS54bKjfLINL4BHtYz0Vz27lRRwew=()
   at #=qmhNvAyztrFon0QQMItVoEw==..ctor()
   at Launcher.LauncherApplication..ctor(SplashScreen #=qf1N4B_PrqOdTNDSUbsv80w==)
   at #=qnTC76DU__og_WMgWCrTYvRcQxL1W079cH4guBwcE_Ec=.#=qFBpVS932WqoZvE_tXrbxgw==()
   at #=qPUOOy9u5HdURknzeezer4ma9AtDiJSThgKqArWsT_GU=.#=qt4kp1W4B7EWJTkNhTHr5uA==()
`````````````````````````````````````````````````````````````````````

`````````````````````````````````````````````````````````````````````
5/29/2018 6:11:23 PM
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully
   at #=q2j__O48iHJA1sJusReyDbbwrLiSkzwNLqrwH6$iE6$o=.#=qY2KRvVSnPBFI46oP9bXkveu3IxN5VFsaRub_4yzULfY=()
   at #=qmhNvAyztrFon0QQMItVoEw==.#=qwPLw4iF7BpHxtYPS54bKjfLINL4BHtYz0Vz27lRRwew=()
   at #=qmhNvAyztrFon0QQMItVoEw==..ctor()
   at Launcher.LauncherApplication..ctor(SplashScreen #=qf1N4B_PrqOdTNDSUbsv80w==)
   at #=qnTC76DU__og_WMgWCrTYvRcQxL1W079cH4guBwcE_Ec=.#=qFBpVS932WqoZvE_tXrbxgw==()
   at #=qPUOOy9u5HdURknzeezer4ma9AtDiJSThgKqArWsT_GU=.#=qt4kp1W4B7EWJTkNhTHr5uA==()
`````````````````````````````````````````````````````````````````````

`````````````````````````````````````````````````````````````````````
5/29/2018 6:12:00 PM
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully
   at #=q2j__O48iHJA1sJusReyDbbwrLiSkzwNLqrwH6$iE6$o=.#=qY2KRvVSnPBFI46oP9bXkveu3IxN5VFsaRub_4yzULfY=()
   at #=qmhNvAyztrFon0QQMItVoEw==.#=qwPLw4iF7BpHxtYPS54bKjfLINL4BHtYz0Vz27lRRwew=()
   at #=qmhNvAyztrFon0QQMItVoEw==..ctor()
   at Launcher.LauncherApplication..ctor(SplashScreen #=qf1N4B_PrqOdTNDSUbsv80w==)
   at #=qnTC76DU__og_WMgWCrTYvRcQxL1W079cH4guBwcE_Ec=.#=qFBpVS932WqoZvE_tXrbxgw==()
   at #=qPUOOy9u5HdURknzeezer4ma9AtDiJSThgKqArWsT_GU=.#=qt4kp1W4B7EWJTkNhTHr5uA==()
`````````````````````````````````````````````````````````````````````

`

**Comment by cairthenn** [comment]
Replace your windower.exe with: http://update.windower.net/Windower.exe and see if this persists. It looks like it's failing to update.

**Comment by Caffeinator1** [comment]
Still hangs up:

`````````````````````````````````````````````````````````````````````
[ 4.3.6326.34361 ] 2018-05-30 02:47:31.9774100 UTC
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): The operation completed
successfully
   at Launcher.Display.GetCurrentDisplayMode()
   at Launcher.Core.SendInitializationReport()
   at Launcher.Core..ctor()
   at Launcher.LauncherApplication..ctor(SplashScreen splashinit,
LauncherOptions options)
   at Launcher.Bootstrap.Main(String[] args)
`````````````````````````````````````````````````````````````````````

**Comment by Caffeinator1** [comment]
Any other ideas? I'm running windows 10 64 bit
Still hangs up and shows the error above.

**Comment by kuroganashi** [comment]
This is an issue with Windower4 files, it needs to be updated from the Source Master and released as a Patch, till then it is unlikely that you be able to use windower4 unless they fix the glitch and release on a new update Patch.

**Comment by mysticat99** [comment]
I'm having the same issue, was working fine yesterday, loged on today and it just crashes on me....
(I uninstalled and reinstalled and the issue still persists)
:( :( :(  this sucks I can't play my game :( :( :(

**Comment by kuroganashi** [comment]
having the same exact issue, it's definitely the back-end from Windower4 that needs to be updated, unfortunately, I no longer have access to it, need to contact Byrth or Aureus.

**Comment by Nifim** [comment]
https://www.ffxiah.com/forum/topic/53127/windower4-wont-download/#3400126

> By Carbuncle.Zeoula 2018-12-26 21:16:18
> Link | Block | Pm | Quote | Reply  | Report | Score: 1 +
>  
> Hello! 
> 
> This was actually happening to me a week ago when I tried moving my computer to my TV - the reason for me was that I manually set my desktop scaling (under NVIDIA Control Panel > Adjust Desktop Size and Position > Scaling). Once I changed it back to "No Scaling" it would then load fine! I'd tried pretty much everything prior to that! 
> 
> Hope that works for you. :)

Can anyone confirm this fixes this issue?

**Comment by Nifim** [comment]
No activity since my last post
