### ISSUE TITLE
TimeoutException when launching POL

### ISSUE THREAD

**Issue by arcanefeenix** [Windower/Issues#1027]
Running Windows 10 Insider Build 18334. I have tried both release and development builds available on main site. I can launch and play FFXI from POLViewer but when I use Windower and choose a profile, it sits at Launching PlayOnline and eventually crashes. I saw a few other issues with similar crashing but they are marked as closed without any replies or there are no followup replies from OP. I saw issue #942 which references a DLL file replacement but I don't see that DLL file anywhere in Windower directory or POL directories. Anyway, here is my crash.log:

`````````````````````````````````````````````````````````````````````
[ 4.3.6774.39167 ] 2019-02-15 17:59:52.0143178 UTC
---------------------------------------------------------------------
System.TimeoutException: The operation has timed out.
   at Launcher.Injector.Inject(SafeSystemHandle process, String hook, Settings settings, TimeSpan timeout)
   at Launcher.Injector.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`````````````````````````````````````````````````````````````````````

`````````````````````````````````````````````````````````````````````
[ 4.3.6774.38955 ] 2019-02-15 18:27:13.2177726 UTC
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at Launcher.Injector.Inject(SafeSystemHandle process, String hook, Settings settings, TimeSpan timeout)
   at Launcher.Injector.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`````````````````````````````````````````````````````````````````````

Here is App Error event in Application Log:
`````````````````````````````````````````````````````````````````````
Faulting application name: Windower.exe, version: 4.3.6774.39167, time stamp: 0x5b50ea5f
Faulting module name: KERNELBASE.dll, version: 10.0.18334.1, time stamp: 0x2fbaf026
Exception code: 0xe0434352
Fault offset: 0x001136d2
Faulting process id: 0x4e38
Faulting application start time: 0x01d4c5581dec2fa5
Faulting application path: D:\Windower\Windower.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: d6393136-b973-4d8a-8e2b-a049156ace45
Faulting package full name: 
Faulting package-relative application ID: 
`````````````````````````````````````````````````````````````````````

**Comment by Nifim** [comment]
The description would appear to be that the hook could not be downloaded, an issue commonly seeing on our support channel on our discord.

If you experience this issue, please read the FAQ on the topic: [No addons listed / Can't download Plugins / Can't launch from Windower / Hook 0.0.0.0 / Inject Error](https://discord.com/channels/338590234235371531/1039568502903816263)
