### ISSUE TITLE
POL doesn't open up. 

### ISSUE THREAD

**Issue by trinironnie** [Windower/Issues#1037]
Currently on laptop. Windower is stuck on launching POL then crashes. 

`````````````````````````````````````````````````````````````````````
[ 4.3.6774.38955 ] 2019-03-19 00:28:00.7388215 UTC
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at Launcher.Injector.Inject(SafeSystemHandle process, String hook, Settings settings, TimeSpan timeout)
   at Launcher.Injector.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`````````````````````````````````````````````````````````````````````

**Comment by Nifim** [comment]
Stale, we do get issues like this from time to time in support but causes are related to the user's system/setup.
