### ISSUE TITLE
Windower 4 not launching POL

### ISSUE THREAD

**Issue by SomeSunBro** [Windower/Issues#1060]
I click to launch, it says launching POL, then goes away and POL never loads. Both POL and FFXI launch and work 100% fine on their own. Below is the crash log i am getting.
Thank you in advance for any help!

[ 4.3.6774.39167 ] 2020-05-17 21:31:38.4673864 UTC
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at Launcher.Injector.Inject(SafeSystemHandle process, String hook, Settings settings, TimeSpan timeout)
   at Launcher.Injector.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`````````````````````````````````````````````````````````````````````

**Comment by RubenatorX** [comment]
This can happen when you have weird things going on with US vs EU client. Find out which one you have installed (or both?) and make sure its set to use one that works.
Meaning like, if registry keys exist for both it maybe trying to launch the wrong one.
Can also happen if you have installed both steam and retail in the past.
Also, if you are trying to use a private server you have to make sure the settings are correct for launching the XiLauncher.
There's a lot of things like this that can cause the problem. Maybe come chat with us in discord

**Comment by SomeSunBro** [comment]
This way my problem. I don't know how, but I had the EU POL client installed. Thank you so much for the response!!
