### ISSUE TITLE
ISSUE WITH 'LAUNCHING PLAYONLINE'

### ISSUE THREAD

**Issue by RyenRaftery** [Windower/Issues#822]
Hello, Windower Community!

My name is Ryen, and this (may as well be) my first post here on Github.

I'm currently running into a problem with the Windower.EXE file--it crashes just as soon as I try to load PlayOnline with my current profile (or, when referring to the GUI, as soon as I select my profile and hit the arrow on the bottom right).

Here's the crash.log dump (this happened over several times with UAC protocols on) I found:

```
[ 4.2.5564.39855 ] 2016-04-18 16:00:10.6958816 UTC
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at #=qPVzKPXreBMK$G_TScC8d1Ctb_fGj44I1J70nspZgfgc=.#=q$pww7u7a8E5KBZ87oKIoig==(String #=qoOfmmNOMqhuJULvaMcWu2w==, #=qdWKs2YH5SnFgXJPCF1szgPXoHSmmSh4DrfoUED_SDBo= #=quTc0RVW0C2_5GERaxMw4LQ==, Boolean #=qhFOX1aUHv3mgiXMa34qGNQ==, TimeSpan #=qFEzHGxyOne7p37rEWbV8$w==)
   at #=qPVzKPXreBMK$G_TScC8d1Ctb_fGj44I1J70nspZgfgc=.#=qsKKl1l0g1HURDWit8B79Fw==(String #=qqKTShJx7xnazuWOpJ6ZDeg==, #=qdWKs2YH5SnFgXJPCF1szgPXoHSmmSh4DrfoUED_SDBo= #=qiV1cyIFi8uzxd23Z9RTz8A==, Boolean #=qvxtyf2yqPR87sOWe96PA4A==)
   at #=qvticlh8sdG9urHCodAc05R$Pt$DrlamfeVITJje_ohY=.#=qxA0hzrjWSVf3wZHstSp6qA==()
   at #=q4ao$U6CJ_ca3wGsQbteYRInNOUKn7px0EZirpC9v2dQ=.#=qRSqZ29WH0ZYrlsLq$sgMxA==(#=q9gJgdStyyOZoRfONVWltog== #=qhFHi0z6eBl3jv5Ev3xCTig==)
   at #=q9gJgdStyyOZoRfONVWltog==.#=q1GDlKxdSu3j9WeEYkyufMQ==()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

Please help me. ><

With thanks,
Ryen

**Comment by Byrth** [comment]
Windower's next minor version update (v4.3) was released today on -dev. To try it out, duplicate your entire Windower directory, then download http://update.windower.net/dev/Windower.exe , replace your existing Windower.exe, and log in. I think there's a pretty good chance that it solves your problem, or at least changes it substantially. You can read more here: #876

I am going to close this now. Please let us know in that thread (and reference this thread) if you still have crash issues.
