### ISSUE TITLE
Windows 10 Insider Preview 14986 - Error Windower to POL

### ISSUE THREAD

**Issue by Sharky86** [Windower/Issues#860]
**Windower crash log**
`````````````````````````````````````````````````````````````````````
[ 4.2.5566.34367 ] 2016-12-22 14:40:54.3875658 UTC
---------------------------------------------------------------------
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at #=qNAoys6l_01$kGiIpO5CrIrRuCZETXesW7sTTEB4Gal4=.#=qwKufhqHv2L66$7gZKs520Q==(String #=qVapXW2awEitORf9JjH2Z6w==, #=qUi9mVlhYoSqC43mrDpN5J16Yw58FdTJQ1Dj528NRqXk= #=qWwywLIiwwd3vAoK7yV7aig==, Boolean #=q4e12V5rphMBC83342At0bA==, TimeSpan #=qrdDuTSk37BW0jiWjut$niw==)
   at #=qNAoys6l_01$kGiIpO5CrIrRuCZETXesW7sTTEB4Gal4=.#=qR5iq8xpXNlQuIPI0q9aQxA==(String #=qdfzSd8SoClgW$QBgtEiLDw==, #=qUi9mVlhYoSqC43mrDpN5J16Yw58FdTJQ1Dj528NRqXk= #=qcFaulCHrc6je5ancV2V21g==, Boolean #=q8T1cwu7h71kjfeHUs9PUww==)
   at #=qbqSo8IYA0eZ3szFRgDRcdDl0c$HwoGg8EDyFYkSzUm0=.#=qYY3EUb3ui0oKDkc9ZKau1g==()
   at #=qaumUmyLhRc4RVHmjcu3ywEw__qp0NHFJ2SZcXwaP1k8=.#=qtIFfxl6XvE0cDoxwPpxmmw==(#=q_TcpwZivXy2jgWJDNlB9MQ== #=qfDp$vC2$EpLjvIoHqgpKzA==)
   at #=q_TcpwZivXy2jgWJDNlB9MQ==.#=qcrAlTroq2NK24O4VOMoI6w==()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Event Viewer Error 1026 .NET Runtime**
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2016-12-23T12:14:34.959014900Z" /> 
  <EventRecordID>4378</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>Sharky86</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Application: Windower.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.InvalidOperationException at #=qNAoys6l_01$kGiIpO5CrIrRuCZETXesW7sTTEB4Gal4=.#=qwKufhqHv2L66$7gZKs520Q==(System.String, #=qUi9mVlhYoSqC43mrDpN5J16Yw58FdTJQ1Dj528NRqXk=, Boolean, System.TimeSpan) at #=qNAoys6l_01$kGiIpO5CrIrRuCZETXesW7sTTEB4Gal4=.#=qR5iq8xpXNlQuIPI0q9aQxA==(System.String, #=qUi9mVlhYoSqC43mrDpN5J16Yw58FdTJQ1Dj528NRqXk=, Boolean) at #=qbqSo8IYA0eZ3szFRgDRcdDl0c$HwoGg8EDyFYkSzUm0=.#=qYY3EUb3ui0oKDkc9ZKau1g==() at #=qaumUmyLhRc4RVHmjcu3ywEw__qp0NHFJ2SZcXwaP1k8=.#=qtIFfxl6XvE0cDoxwPpxmmw==(#=q_TcpwZivXy2jgWJDNlB9MQ==) at #=q_TcpwZivXy2jgWJDNlB9MQ==.#=qcrAlTroq2NK24O4VOMoI6w==() at System.Threading.ThreadHelper.ThreadStart_Context(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.ThreadHelper.ThreadStart()</Data> 
  </EventData>
  </Event>

**Event Viewer Application Error 1000 (100)**
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2016-12-23T12:14:35.025021700Z" /> 
  <EventRecordID>4379</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>Sharky86</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Windower.exe</Data> 
  <Data>4.2.5566.34367</Data> 
  <Data>55183efb</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.14986.1000</Data> 
  <Data>96defb21</Data> 
  <Data>e0434352</Data> 
  <Data>000ee512</Data> 
  <Data>22b0</Data> 
  <Data>01d25d161c3cbd52</Data> 
  <Data>C:\Windower4\Windower.exe</Data> 
  <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data> 
  <Data>cd157a58-a5ad-4dd5-aacf-be07edc7edd7</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by alphaONE2** [comment]
Looks like Windower couldn't find where you have PlayOnline Viewer installed. If you're using the Steam version make sure you run it from Steam manually at least once. Otherwise, make double check your FFXI installation, you may need to reinstall, or verify that the registry is set up correctly.

**Comment by Byrth** [comment]
This problem has been supplanted by #867 , which we seem to be well on our way to solving, so I'm going to close this issue.
