### ISSUE TITLE
pol.exe Entry Point Not Found (launching POL from Windower)

### ISSUE THREAD

**Issue by dwlexmaster** [Windower/Issues#884]
Hello all -- so a few facts about my setup, etc. Mocks are understood given my severely outdated system, etc. However, everything worked just fine until today (last successful login was this morning 4/27/17). I'm not sure what the fix is, and I greatly welcome and appreciate any feedback you have. 
 
Windows XP Home SP3
Dell Vostro 1500
 
 
When i open Windower 4, and proceeded to click to launch POL, the following error shows up: "The procedure entry point GetThreadId could not be located in the dynamic link library KERNEL32.dll". After clicking ok to the error prompt, POL opens and loads just regularly (without Windower). I've tried reinstalling Windower, but with no change.
 
I've read through a number of threads here and on Github, and several responses from Byrth and alphaONE2. Particularly this one: 
https://github.com/W...ues/issues/778.
 
I've never installed another version of POL or FFXI (EU etc), only US. The registry settings are also correct per this thread: 
http://forums.window...es-upon-launch/
 
 
Also tried updating Windower per the instructions in this thread, but still having the same issue: https://github.com/W...sues/issues/792
 
crash.log:
 
[ 4.3.6326.35073 ] 2017-04-27 23:37:34.9843750 UTC
---------------------------------------------------------------------
System.TimeoutException: The operation has timed out.
   at Launcher.PlayOnlineLauncher.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
 
 
Thank you in advance for any assistance.

**Comment by wxm197745** [comment]
I also encountered the same problem with you, how can we solve now?

**Comment by coroug** [comment]
same problem；；；；

**Comment by dwlexmaster** [comment]
I was able to bypass this for now. Please refer to this post -- [http://forums.windower.net/index.php?/topic/1250-polexe-entry-point-not-found-launching-pol-from-windower/](url)

**Comment by coroug** [comment]
Windower will not open PlayOnline;;

**Comment by Stratusx** [comment]
[ 4.3.6326.35073 ] 2017-04-28 11:01:40.4043469 UTC
---------------------------------------------------------------------
System.TimeoutException: The operation has timed out.
   at Launcher.PlayOnlineLauncher.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`````````````````````````````````````````````````````````````````````

`````````````````````````````````````````````````````````````````````
[ 4.3.6326.35073 ] 2017-04-28 11:02:14.4668469 UTC
---------------------------------------------------------------------
System.TimeoutException: The operation has timed out.
   at Launcher.PlayOnlineLauncher.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`````````````````````````````````````````````````````````````````````

`````````````````````````````````````````````````````````````````````
[ 4.3.6326.35073 ] 2017-04-28 11:34:16.8437500 UTC
---------------------------------------------------------------------
System.TimeoutException: The operation has timed out.
   at Launcher.PlayOnlineLauncher.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`````````````````````````````````````````````````````````````````````

`````````````````````````````````````````````````````````````````````
[ 4.3.6326.35073 ] 2017-04-29 02:05:43.0891209 UTC
---------------------------------------------------------------------
System.TimeoutException: The operation has timed out.
   at Launcher.PlayOnlineLauncher.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`````````````````````````````````````````````````````````````````````

`````````````````````````````````````````````````````````````````````
[ 4.3.6328.2702 ] 2017-04-30 04:27:37.3593750 UTC
---------------------------------------------------------------------
System.EntryPointNotFoundException: Unable to find an entry point named 'Wow64GetThreadContext' in DLL 'kernel32.dll'.
   at Windower.Core.NativeMethods.Wow64GetThreadContext(SafeWaitHandle hThread, IntPtr lpContext)
   at Windower.Core.Injector.GetInstructionPointer()
   at Windower.Core.Injector.RunProcessInitialization()
   at Windower.Core.Injector.Inject(String dllPath)
   at Launcher.PlayOnlineLauncher.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`````````````````````````````````````````````````````````````````````

**Comment by Nifim** [comment]
Fix: https://forums.windower.net/index.php@sharelink=download%3BaHR0cDovL2ZvcnVtcy53aW5kb3dlci5uZXQvaW5kZXgucGhwPy90b3BpYy82NTctZ2FtZS1jcmFzaC1vbi16b25lLWNoYW5nZS9wYWdlLTM,%3BZ2FtZSBjcmFzaCBvbiB6b25lIGNoYW5nZQ,,.html
