### ISSUE TITLE
Windower crashing on startup

### ISSUE THREAD

**Issue by simonkeenlyside** [Windower/Issues#887]
I open windower like normal, and it crashes before I get to the login page on POL. Only started last night. Crash dump below.

[ 4.3.6326.35073 ] 2017-04-28 05:09:57.8124695 UTC
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): Only part of a ReadProcessMemory or WriteProcessMemory request was completed
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.ProcessManager.GetModuleInfos(Int32 processId)
   at System.Diagnostics.Process.get_Modules()
   at Windower.Core.Injector.GetRemoteFunctionAddress(String module, String function)
   at Windower.Core.Injector.Inject(String dllPath)
   at Launcher.PlayOnlineLauncher.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`````````````````````````````````````````````````````````````````````

`````````````````````````````````````````````````````````````````````
[ 4.3.6326.35073 ] 2017-04-29 01:03:38.0679160 UTC
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): A 32 bit processes cannot access modules of a 64 bit process.
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.ProcessManager.GetModuleInfos(Int32 processId)
   at System.Diagnostics.Process.get_Modules()
   at Windower.Core.Injector.GetRemoteFunctionAddress(String module, String function)
   at Windower.Core.Injector.Inject(String dllPath)
   at Launcher.PlayOnlineLauncher.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`````````````````````````````````````````````````````````````````````

**Comment by wxm197745** [comment]
How to solve？

**Comment by wxm197745** [comment]
I also encountered the same problem with you, how can we solve now?

**Comment by Lithgen** [comment]
same problem  ; ;

**Comment by joshk6656** [comment]
Could you guys please re-run launcher and see if this is resolved?

**Comment by simonkeenlyside** [comment]
Mine is resolved!! Thank you!

**Comment by joshk6656** [comment]
Closing as reporter reported his issue corrected.
