### ISSUE TITLE
Hook issue: 4.3.0.6 (Parameter is incorrect)

### ISSUE THREAD

**Issue by Lvyermarc** [Windower/Issues#890]
Unable to start successfully launch windower, today 4-29-2017. 
Consistent problem, happens every time. 
I am running Windows 10 Pro, 64-bit
As far as I can tell, I'm not running anything in compatibility  mode.

[ 4.3.6328.2702 ] 2017-04-29 22:15:58.8137553 UTC
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): The parameter is incorrect
   at Windower.Core.Injector.SetMemoryAccess(IntPtr address, Int32 length, UInt32 access)
   at Windower.Core.Injector.RunProcessInitialization()
   at Windower.Core.Injector.Inject(String dllPath)
   at Launcher.PlayOnlineLauncher.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

I also had the problem with Hook 4.3.0.5 (Attempt to access invalid address) earlier today before the 4.3.0.6 patch was added. That seems to have gone away. Now I have the above problem.

**Comment by Byrth** [comment]
Did you already install the Creators Update for Windows 10?

As an aside, 0x80004005 is E_FAIL Unspecified error

**Comment by Fizztastic** [comment]
I'm getting the same crash dump on Windows 7 x64 when using Windower in conjunction with XiLoader.

**Comment by Byrth** [comment]
Lvyermarc, are you also using xiLoader?

**Comment by Lvyermarc** [comment]
Yes, also using xiLoader

**Comment by Lvyermarc** [comment]
Windows Update gives me an option to get an early Win 10 Creators Update - I have not pursued this in any way, although automatic updates are enabled.

For Windows 10 Pro, last updates were:

- Win 10 Creators Update Privacy Settings for x64-based Systems (KB4013214), 4/24/2017
- Win 10 Version 1607 for x64-based Systems (KB3150513), 4/22/2017

**Comment by cairface** [comment]
The changes that caused this issue were reverted as far as I'm aware. I think this can be closed? Any feedback from anyone who uses xiloader?

**Comment by z16** [comment]
You're right, Sir!
