### ISSUE TITLE
Windower Crashing While Launching PlayOnline

### ISSUE THREAD

**Issue by Sinnersslayer** [Windower/Issues#980]
Hi,

Windower crashing on every attempt to run POL.
Here is what crash.log file contains:

```[ 4.3.6632.29121 ] 2018-02-28 10:38:48.4338108 UTC
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): Access denied.
   w Launcher.Injector.Inject(SafeSystemHandle process, String hook, Settings settings, TimeSpan timeout)
   w Launcher.Injector.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   w Launcher.Tasks.LaunchTask.Run()
   w Launcher.Tasks.Task.Run(Core core)
   w Launcher.Core.Run()
   w System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
```

**Comment by notnate75** [comment]
This sounds like my issue; here is the dmp file:
https://drive.google.com/file/d/1Tct3CUjqVo2dQUNOcLetbespVS_Oe_Kh/view?usp=sharing

**Comment by seiverdamross** [comment]
also having this issue

`````````````````````````````````````````````````````````````````````
[ 4.3.6774.39167 ] 2018-08-06 01:47:03.0283823 UTC
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at Launcher.Injector.Inject(SafeSystemHandle process, String hook, Settings settings, TimeSpan timeout)
   at Launcher.Injector.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`````````````````````````````````````````````````````````````````````

**Comment by spicy-tonkotsu** [comment]
Any updates on this?  Getting the same error.

"System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at Launcher.Injector.Inject(SafeSystemHandle process, String hook, Settings settings, TimeSpan timeout)
   at Launcher.Injector.Launch(String hook, Profile profile, Boolean debug, TimeSpan timeout)
   at Launcher.Tasks.LaunchTask.Run()
   at Launcher.Tasks.Task.Run(Core core)
   at Launcher.Core.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()"

**Comment by Nifim** [comment]
This is caused by many different issue, they usually are related to the user setup. If you experience an issue like this please seek assistance on our discord support channel
