### ISSUE TITLE
windower4 crashes on startup

### ISSUE THREAD

**Issue by pc1971** [Windower/Issues#981]
running windower 4 on a dell laptop with windows 7 pro, completely updated service packs.

error message i found in the crash file.

`````````````````````````````````````````````````````````````````````
[ 4.3.6632.29121 ] 2018-02-28 12:55:47.0102301 UTC
---------------------------------------------------------------------
System.NotSupportedException: The requested security protocol is not supported.
   at System.Net.ServicePointManager.ValidateSecurityProtocol(SecurityProtocolType value)
   at Launcher.LauncherApplication..ctor(SplashScreen splashinit, LauncherOptions options)
   at Launcher.Bootstrap.Main(String[] args)
`````````````````````````````````````````````````````````````````````

**Comment by z16** [comment]
Try installing the .NET Framework 4.5, it should be this link:
https://www.microsoft.com/en-us/download/details.aspx?id=30653

See if that helps.

**Comment by Hoiy** [comment]
@z16 Thanks! It solved my crash on windows 7
